void KbdLow(int KbdPin);
void KbdHigh(int KbdPin);
void AMouseWrite();
byte MouseReadPS2();
void MouseWritePS2(byte value);
void MouseHostToDevicePS2();
void SerMouseWrite();
uint8_t JoyCalibrate(uint8_t value, uint8_t center);
void JoyWrite();
void HardResetAmiga();
byte KbdWriteAmigaNoSpecialHandling(byte value,byte make);
void KbdPowerUpAmiga(byte CAA);
byte ResetWarningAmiga();
void KbdPutBufferAT(byte value,byte make);
byte KbdReadAT();
byte ATKbdTypematicKey(byte USBScanCode);
void sendToTandy(byte value);
byte ADBSync();
byte ADBReadCommand();
void ADBWriteByte(byte value);
void ADBWriteTwoBytes(byte value1,byte value2);
void MouseWriteADB();
void MouseWriteADBReg3();
